yasnippet 0.10.0
Switch to ELPA tarball since a yasmate submodule fails fsck:

```
Cloning into '/Users/cat/Library/Caches/Homebrew/yasnippet--git/yasmate/bundles/rails-tmbundle'...
error: object 060551a1f77fa67bad78c9a2076d934a8d858c88: zeroPaddedFilemode: contains zero-padded file modes
fatal: Error in object
fatal: index-pack failed
fatal: clone of 'https://github.com/textmate/ruby-on-rails-tmbundle.git' into submodule path '/Users/cat/Library/Caches/Homebrew/yasnippet--git/yasmate/bundles/rails-tmbundle' failed
```